### ISSUE TITLE
Plugin just sends a ton of notifications

### ISSUE THREAD

**Issue by YvesW** [Th3mike/Vengeance-Helper#3]
When I enable the plugin, without ever casting vengeance or even being on lunars, it spams a crap ton of notifications to the notification queue. These of course keep popping up, even after the plugin is disabled. The only way to get rid of the list of notifications, is to disallow and reallow RL to send notifications.

**Comment by Simpuhl** [comment]
This also happened to me a few times, it freezes the screen and them spams like 50 all at once. Only happened when logging in
