### ISSUE TITLE
Add additional option: Only Show when on Lunar Spell book 

### ISSUE THREAD

**Issue by Simpuhl** [Th3mike/Vengeance-Helper#4]
Add additional option: Only Show when on Lunar Spell book 

Simple checkbox. The thrall addon does this also.

**Comment by Simpuhl** [comment]
Also, ability to customize the words it says? I'd prefer something shorter like "Cast Vengeance!" so the box isn't so large

**Comment by Th3mike** [comment]
Yo im checking this!
